final lessons = {
  "schools": [
    'Nursery',
    'Primary',
    'O-Level',
    'A-Level',
    'Skill-Based Learning',
  ]
};

final classes = {
  'Nursery': [
    "English Medium",
    "Swahili Medium",
  ],
  'Primary': [
    "Standard I",
    "Standard II",
    "Standard III",
    "Standard IV",
    "Standard VII",
  ],
  'O-Level': [
    "Form I",
    "Form II",
    "Form III",
    "Form IV",
  ],
  'A-Level': [
    "Form V",
    "Form VI",
  ],
  'Skill-Based Learning': [
    "Computer Literacy",
    "English Course",
  ],
};

final subjects = {
  "English Medium": [
    "Language and Communication",
    "Early Life Skills",
    "Health and Environment",
    "Early Arithmetic",
    "Relating with Others",
  ],
  "Swahili Medium": [
    "Language and Communication",
    "Early Life Skills",
    "Health and Environment",
    "Early Arithmetic",
    "Relating with Others",
  ],
  "Standard I": [
    "Arithmetic",
    "Writting",
    "Reading",
    "Health and Environment",
    "Sport and Arts",
  ],
  "Standard II": [
    "Arithmetic",
    "Writting",
    "Reading",
    "Health and Environment",
    "Sport and Arts",
  ],
  "Standard III": [
    "Mathematics",
    "English",
    "Kiswahili",
    "Social Studies",
    "Science and Technology",
    "Civics and Moral Education",
    "Comunity Knowledge",
  ],
  "Standard IV": [
    "Mathematics",
    "English",
    "Kiswahili",
    "Social Studies",
    "Science and Technology",
    "Civics and Moral Education",
    "Comunity Knowledge",
  ],
  "Standard VII": [
    "Mathematics",
    "English",
    "Kiswahili",
    "Social Studies",
    "Science and Technology",
    "Civics and Moral Education",
    "Comunity Knowledge",
  ],
  "Form I": [
    "History",
    "Geography",
    "Kiswahili",
    "English Language",
    "Literature",
    "Bible Study",
    "Islamic Study",
    "Physics",
    "Chemistry",
    "Biology",
    "Mathematics",
    "Additional Mathematics",
    "Computer Science",
    "Economics",
    "Commerce",
    "Accounts",
  ],
  "Form II": [
    "History",
    "Geography",
    "Kiswahili",
    "English Language",
    "Literature",
    "Bible Study",
    "Islamic Study",
    "Physics",
    "Chemistry",
    "Biology",
    "Mathematics",
    "Additional Mathematics",
    "Computer Science",
    "Economics",
    "Commerce",
    "Accounts",
  ],
  "Form III": [
    "History",
    "Geography",
    "Kiswahili",
    "English Language",
    "Literature",
    "Bible Study",
    "Islamic Study",
    "Physics",
    "Chemistry",
    "Biology",
    "Mathematics",
    "Additional Mathematics",
    "Computer Science",
    "Economics",
    "Commerce",
    "Accounts",
  ],
  "Form IV": [
    "History",
    "Geography",
    "Kiswahili",
    "English Language",
    "Literature",
    "Bible Study",
    "Islamic Study",
    "Physics",
    "Chemistry",
    "Biology",
    "Mathematics",
    "Additional Mathematics",
    "Computer Science",
    "Economics",
    "Commerce",
    "Accounts",
  ],
  "Form V": [
    "History",
    "Geography",
    "Kiswahili",
    "English",
    "Literature",
    "Physics",
    "Chemistry",
    "Biology",
    "Agriculture",
    "Mathematics",
    "BAM",
    "Computer Science",
    "Economics",
    "Commerce",
    "Accounts",
    'General Studies',
  ],
  "Form VI": [
    "History",
    "Geography",
    "Kiswahili",
    "English",
    "Literature",
    "Physics",
    "Chemistry",
    "Biology",
    "Agriculture",
    "Mathematics",
    "BAM",
    "Computer Science",
    "Economics",
    "Commerce",
    "Accounts",
    'General Studies',
  ],
  "Computer Literacy": [
    "What is a Computer",
    "Computer Components",
    "Microsoft Office",
    "Command Prompt",
    "Windows in a Nutshell",
    "Other Operating Systems",
    "OS Installation",
    "What are Drivers",
    "Drivers Installation",
  ],
  "English Course": [
    "Course Introduction",
    "Reading",
    "Writing",
    "Practice",
    "Grammar",
    "Tesnses",
  ],
};
