final lessons = {
  "schools": [
    'Nursery',
    'Primary',
    'O-Level',
    'A-Level',
    'Skill-Based Learning',
  ]
};

final classes = {
  'Nursery': [
    "English Medium",
    "Swahili Medium",
  ],
  'Primary': [
    "Standard I",
    "Standard II",
    "Standard III",
    "Standard IV",
    "Standard VII",
  ],
  'O-Level': [
    "Form I",
    "Form II",
    "Form III",
    "Form IV",
  ],
  'A-Level': [
    "Form V",
    "Form VI",
  ],
  'Skill-Based Learning': [
    "Computer Literacy",
    "English Course",
  ],
};

final subjects = {
  "English Medium": [
    "Language and Communication",
    "Early Life Skills",
    "Health and Environment",
    "Early Arithmetic",
    "Relating with Others",
  ],
  "Swahili Medium": [
    "Language and Communication",
    "Early Life Skills",
    "Health and Environment",
    "Early Arithmetic",
    "Relating with Others",
  ],
  "Standard I": [
    "Arithmetic",
    "Writting",
    "Reading",
    "Health and Environment",
    "Sport and Arts",
  ],
  "Standard II": [
    "Arithmetic",
    "Writting",
    "Reading",
    "Health and Environment",
    "Sport and Arts",
  ],
  "Standard III": [
    "Mathematics",
    "English",
    "Kiswahili",
    "Social Studies",
    "Science and Technology",
    "Civics and Moral Education",
    "Comunity Knowledge",
  ],
  "Standard IV": [
    "Mathematics",
    "English",
    "Kiswahili",
    "Social Studies",
    "Science and Technology",
    "Civics and Moral Education",
    "Comunity Knowledge",
  ],
  "Standard VII": [
    "Mathematics",
    "English",
    "Kiswahili",
    "Social Studies",
    "Science and Technology",
    "Civics and Moral Education",
    "Comunity Knowledge",
  ],
  "Form I": [
    "History",
    "Geography",
    "Kiswahili",
    "English Language",
    "Literature",
    "Bible Study",
    "Islamic Study",
    "Physics",
    "Chemistry",
    "Biology",
    "Mathematics",
    "Additional Mathematics",
    "Computer Science",
    "Economics",
    "Commerce",
    "Accounts",
  ],
  "Form II": [
    "History",
    "Geography",
    "Kiswahili",
    "English Language",
    "Literature",
    "Bible Study",
    "Islamic Study",
    "Physics",
    "Chemistry",
    "Biology",
    "Mathematics",
    "Additional Mathematics",
    "Computer Science",
    "Economics",
    "Commerce",
    "Accounts",
  ],
  "Form III": [
    "History",
    "Geography",
    "Kiswahili",
    "English Language",
    "Literature",
    "Bible Study",
    "Islamic Study",
    "Physics",
    "Chemistry",
    "Biology",
    "Mathematics",
    "Additional Mathematics",
    "Computer Science",
    "Economics",
    "Commerce",
    "Accounts",
  ],
  "Form IV": [
    "History",
    "Geography",
    "Kiswahili",
    "English Language",
    "Literature",
    "Bible Study",
    "Islamic Study",
    "Physics",
    "Chemistry",
    "Biology",
    "Mathematics",
    "Additional Mathematics",
    "Computer Science",
    "Economics",
    "Commerce",
    "Accounts",
  ],
  "Form V": [
    "History",
    "Geography",
    "Kiswahili",
    "English",
    "Literature",
    "Physics",
    "Chemistry",
    "Biology",
    "Agriculture",
    "Mathematics",
    "BAM",
    "Computer Science",
    "Economics",
    "Commerce",
    "Accounts",
    'General Studies',
  ],
  "Form VI": [
    "History",
    "Geography",
    "Kiswahili",
    "English",
    "Literature",
    "Physics",
    "Chemistry",
    "Biology",
    "Agriculture",
    "Mathematics",
    "BAM",
    "Computer Science",
    "Economics",
    "Commerce",
    "Accounts",
    'General Studies',
  ],
  "Computer Literacy": [
    "What is a Computer",
    "Computer Components",
    "Microsoft Office",
    "Command Prompt",
    "Windows in a Nutshell",
    "Other Operating Systems",
    "OS Installation",
    "What are Drivers",
    "Drivers Installation",
  ],
  "English Course": [
    "Course Introduction",
    "Reading",
    "Writing",
    "Practice",
    "Grammar",
    "Tesnses",
  ],
};

final topics = {
  "Computer Literacy": [
    "What is a Computer",
    "Computer Components",
    "Microsoft Office",
    "Command Prompt",
    "Windows in a Nutshell",
    "Other Operating Systems",
    "OS Installation",
    "What are Drivers",
    "Drivers Installation",
  ],
  "English Course": [
    "Course Introduction",
    "Reading",
    "Writing",
    "Practice",
    "Grammar",
    "Tesnses",
  ],
  "Mathematics": [
    "Numbers and Operations",
    "Algebraic Expressions",
    "Geometry and Shapes",
    "Trigonometry",
    "Statistics and Probability",
    "Functions and Graphs",
    "Linear and Quadratic Equations",
    "Matrices and Determinants",
    "Differentiation and Integration",
    "Vectors and Coordinate Geometry"
  ],
  "English Language": [
    "Grammar Rules",
    "Sentence Structure",
    "Parts of Speech",
    "Tenses and Verb Forms",
    "Reading Comprehension",
    "Essay Writing",
    "Letter Writing",
    "Vocabulary Building",
    "Public Speaking",
    "Listening Skills"
  ],
  "Kiswahili": [
    "Sarufi (Grammar)",
    "Matumizi ya Lugha (Language Usage)",
    "Ufahamu wa Kusoma (Reading Comprehension)",
    "Insha (Essay Writing)",
    "Mashairi (Poetry)",
    "Fasihi Simulizi (Oral Literature)",
    "Tamthiliya (Drama)",
    "Misemo na Methali (Idioms and Proverbs)",
    "Matumizi ya Maneno (Word Usage)"
  ],
  "Physics": [
    "Measurements and Units",
    "Forces and Motion",
    "Work, Energy, and Power",
    "Waves and Sound",
    "Light and Optics",
    "Thermodynamics",
    "Electricity and Magnetism",
    "Modern Physics",
    "Nuclear Physics",
    "Fluid Mechanics"
  ],
  "Chemistry": [
    "Atomic Structure",
    "Chemical Bonding",
    "States of Matter",
    "Stoichiometry",
    "Chemical Reactions",
    "Acids, Bases, and Salts",
    "Organic Chemistry",
    "Electrochemistry",
    "Periodic Table Trends",
    "Industrial Chemistry"
  ],
  "Biology": [
    "Cell Structure and Function",
    "Human Anatomy and Physiology",
    "Genetics and Heredity",
    "Microbiology",
    "Plant Physiology",
    "Ecology and Environment",
    "Reproduction and Growth",
    "Health and Hygiene",
    "Biotechnology",
    "Evolution and Adaptation"
  ],
  "History": [
    "Ancient Civilizations",
    "Colonialism and Its Effects",
    "World Wars",
    "African Kingdoms",
    "Independence Movements",
    "Cold War Politics",
    "Economic History",
    "Industrial Revolution",
    "Slavery and Trade",
    "Modern Global Issues"
  ],
  "Geography": [
    "Earth and Universe",
    "Weather and Climate",
    "Natural Resources",
    "Map Reading and Interpretation",
    "Population and Settlement",
    "Economic Activities",
    "Environmental Conservation",
    "Geographical Information Systems (GIS)",
    "Urbanization and Development",
    "Disaster Management"
  ],
  "Civics and Moral Education": [
    "Citizenship and Rights",
    "Government and Leadership",
    "Constitution and Law",
    "Human Rights and Democracy",
    "Community Service",
    "Cultural Diversity",
    "National Symbols and Identity",
    "Conflict Resolution",
    "Ethics and Integrity",
    "Social Justice and Responsibility"
  ],
  "Commerce": [
    "Introduction to Commerce",
    "Trade and Exchange",
    "Business Ownership",
    "Marketing Strategies",
    "Money and Banking",
    "Insurance and Risk Management",
    "Stock Exchange and Investments",
    "Entrepreneurship",
    "Consumer Protection",
    "International Trade"
  ],
  "Economics": [
    "Basic Economic Concepts",
    "Demand and Supply",
    "Market Structures",
    "Economic Growth and Development",
    "Inflation and Unemployment",
    "Public Finance",
    "Monetary and Fiscal Policies",
    "International Economics",
    "Microeconomics vs. Macroeconomics",
    "Sustainable Development"
  ],
  "Accounts": [
    "Introduction to Accounting",
    "Double Entry System",
    "Financial Statements",
    "Profit and Loss Account",
    "Balance Sheet",
    "Bank Reconciliation",
    "Depreciation and Amortization",
    "Budgeting and Forecasting",
    "Taxation and Auditing",
    "Accounting Software"
  ],
  "Computer Science": [
    "Introduction to Computers",
    "Operating Systems",
    "Programming Basics",
    "Database Management",
    "Networking Fundamentals",
    "Cybersecurity and Encryption",
    "Web Development",
    "Artificial Intelligence",
    "Software Engineering",
    "Mobile App Development"
  ],
  "Literature": [
    "Poetry Analysis",
    "Prose and Fiction",
    "Drama and Plays",
    "Themes and Characterization",
    "Figurative Language",
    "Literary Criticism",
    "African Literature",
    "European Literature",
    "Symbolism in Literature",
    "Comparative Literature"
  ],
  "Agriculture": [
    "Introduction to Agriculture",
    "Crop Production",
    "Animal Husbandry",
    "Soil Science",
    "Agribusiness and Marketing",
    "Pest and Disease Control",
    "Irrigation and Water Management",
    "Food Processing and Storage",
    "Sustainable Farming Practices",
    "Genetically Modified Crops"
  ],
  "Bible Study": [
    "Old Testament Overview",
    "New Testament Overview",
    "Parables of Jesus",
    "Christian Ethics",
    "The Life of Jesus",
    "Biblical Prophecies",
    "Apostles and Early Church",
    "Prayer and Worship",
    "Faith and Salvation",
    "Christian Leadership"
  ],
  "Islamic Study": [
    "Life of Prophet Muhammad",
    "Five Pillars of Islam",
    "Islamic Ethics and Morality",
    "Islamic Law (Sharia)",
    "The Holy Quran",
    "Hadith and Sunnah",
    "Islamic History",
    "Faith and Worship",
    "Islamic Civilization",
    "Contemporary Issues in Islam"
  ],
  "General Studies": [
    "Current Affairs",
    "Environmental Issues",
    "Cultural Awareness",
    "Globalization and Development",
    "Science and Technology in Society",
    "Media and Communication",
    "Human Rights and Responsibilities",
    "Leadership and Governance",
    "Ethical Decision Making",
    "Personal Finance and Planning"
  ],
};
